[platformio]
src_dir = .

[env:esp32-c3]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
upload_port = COM28
monitor_port = COM28
monitor_speed = 115200
upload_resetmethod = usb

# Monitor settings
monitor_filters = default
monitor_echo = yes
monitor_eol = LF
